export const UI_LIMITS = {
  USER_LIST_PAGE_SIZE: 10,
  ADMIN_TABLE_PAGE_SIZE: 20,
  PASSWORD_MIN_LENGTH: 6,
  FRIEND_SEARCH_DEBOUNCE_MS: 600,
  SEARCH_DEBOUNCE_MS: 500,
  SIDEBAR_NAVIGATION_DELAY_MS: 300,
  UNREAD_BADGE_MAX: 99,
  ADMIN_AUTOCOMPLETE_LIMIT: 10,
} as const;
